language: php

dist: trusty

sudo: false

php:
    - 7.1
    - 7.2

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - composer install --no-interaction --prefer-dist

#before_script:
#    # Run webserver
#    - (cd tests/Application && bin/console server:run 127.0.0.1:8080 -d web --env=test --quiet > /dev/null 2>&1 &)

script:
    - composer validate --strict
#    - bin/phpstan.phar analyse -c phpstan.neon -l max src/
    - bin/phpspec run --no-interaction -f dot
#    - bin/behat --strict -vvv --no-interaction || bin/behat --strict -vvv --no-interaction --rerun

